"""Validated interchange adapter for an isolated RacketVision worker."""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
from typing import Iterator

import numpy as np

from .ball_tracking import BallObservation
from .interaction_tracking import RacketPoseObservation


SCHEMA_VERSION = "seima.racketvision-cache.v1"
UPSTREAM_COMMIT = "c44af2a08524d3cb54d818f19686f4cdea4d2793"


@dataclass(frozen=True)
class RacketVisionFrame:
    frame_index: int
    timestamp_s: float
    ball_candidates: tuple[BallObservation, ...]
    rackets: tuple[RacketPoseObservation, ...]
    inference_ms: float | None = None


def sha256_file(path: str | Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_cache(path: str | Path, *, expected_frames: int | None = None,
               verify_manifest: bool = True) -> list[RacketVisionFrame]:
    path = Path(path)
    manifest_path = path.with_suffix(".manifest.json")
    if verify_manifest and manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        if manifest.get("schema_version") != SCHEMA_VERSION:
            raise ValueError("RacketVision cache manifest has an unsupported schema")
        if manifest.get("upstream_commit") != UPSTREAM_COMMIT:
            raise ValueError("RacketVision cache was generated by an unpinned upstream commit")
        if manifest.get("cache_sha256") != sha256_file(path):
            raise ValueError("RacketVision cache hash does not match its manifest")
    frames = []
    with path.open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            raw = json.loads(line)
            if raw.get("schema_version") != SCHEMA_VERSION:
                raise ValueError(f"unsupported RacketVision cache schema on line {line_number}")
            timestamp = float(raw["timestamp_s"])
            balls = tuple(BallObservation(
                timestamp, np.array([item["x_px"], item["y_px"]]), float(item["confidence"]),
                size_px=item.get("size_px"),
                blur_vector_px=item.get("blur_vector_px"), source=item.get("source", "racketvision_balltrack")
            ) for item in raw.get("ball_candidates", []))
            rackets = tuple(RacketPoseObservation(
                timestamp, np.asarray(item["bbox_xyxy"], dtype=float),
                np.asarray(item["keypoints_xy"], dtype=float),
                np.asarray(item["keypoint_scores"], dtype=float),
                float(item["confidence"]), item.get("source", "racketvision_racketpose")
            ) for item in raw.get("rackets", []))
            frames.append(RacketVisionFrame(int(raw["frame"]), timestamp, balls, rackets,
                                             raw.get("inference_ms")))
    if any(frame.frame_index != index for index, frame in enumerate(frames)):
        raise ValueError("RacketVision cache frames must be contiguous and zero based")
    if expected_frames is not None and len(frames) != expected_frames:
        raise ValueError(f"RacketVision cache has {len(frames)} frames, expected {expected_frames}")
    return frames


def write_cache(path: str | Path, frames: Iterator[dict], metadata: dict) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        for frame in frames:
            stream.write(json.dumps({"schema_version": SCHEMA_VERSION, **frame}, ensure_ascii=False) + "\n")
    manifest_path = path.with_suffix(".manifest.json")
    manifest_path.write_text(json.dumps({
        "schema_version": SCHEMA_VERSION,
        "upstream_commit": UPSTREAM_COMMIT,
        "cache_sha256": sha256_file(path),
        **metadata,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest_path
