"""Small deterministic smoke test for the physics-informed ball tracker.

Run from repository root:
    python scripts/validate_ball_tracking_synthetic.py

This does not validate the model against a real ball. It only checks whether the
numerical fitter can recover a known synthetic trajectory generated by the same
physics model.
"""
from __future__ import annotations

import json
from pathlib import Path
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from seima_mocap.ball_tracking import (
    BallPhysicalParams,
    BallState,
    WorldBallObservation,
    fit_initial_state_world,
    propagate_state,
)


def main() -> None:
    params = BallPhysicalParams.from_json(ROOT / "config/ball_tracking_defaults.json")
    params = BallPhysicalParams(**{**params.__dict__, "magnus_enabled": False})

    truth = BallState(
        position_m=np.array([0.20, -0.15, 0.45]),
        velocity_m_s=np.array([9.0, 0.8, 4.2]),
        timestamp_s=0.0,
    )
    times = np.linspace(0.0, 0.40, 17)
    rng = np.random.default_rng(7)
    observations = []
    for index, timestamp in enumerate(times):
        state = propagate_state(truth, float(timestamp), params)
        noise = rng.normal(0.0, 0.0015, 3)
        confidence = 0.35 if index in (6, 11) else 1.0
        if index == 6:
            noise += np.array([0.025, -0.010, 0.015])
        observations.append(WorldBallObservation(float(timestamp), state.position_m + noise, confidence))

    guess = BallState(
        truth.position_m + np.array([0.05, -0.04, 0.04]),
        truth.velocity_m_s + np.array([-1.2, 0.5, -0.7]),
        0.0,
    )
    result = fit_initial_state_world(
        observations,
        guess,
        params,
        huber_delta_m=0.015,
        max_iterations=30,
    )

    report = {
        "scope": "synthetic numerical smoke test; not empirical validation",
        "truth_position_m": truth.position_m.tolist(),
        "estimated_position_m": result.state.position_m.tolist(),
        "truth_velocity_m_s": truth.velocity_m_s.tolist(),
        "estimated_velocity_m_s": result.state.velocity_m_s.tolist(),
        "rmse_m": result.rmse_m,
        "iterations": result.iterations,
        "converged": result.converged,
        "magnus_enabled": result.params.magnus_enabled,
    }
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
